events {
    worker_connections 1024;
}

http {
    upstream python_backend {
        # Docker's internal DNS automatically resolves 'web' to the IPs of all 8 replicas
        server web:5000;
    }

    server {
        listen 5050;
        server_name kinetic-api.gidraf.dev;

        location / {
            proxy_pass http://python_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            
            # WebSocket / SSE support (Crucial for your live match analytics streams)
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_read_timeout 86400;
        }
    }
}