"""
probe_utils.py  (Playwright edition)
=====================================
Drop-in replacement — same _probe() signature, same response dict shape.

Why Playwright:
  Sites like 1xbet use per-request HMAC signatures (x-hd) generated by
  their own JavaScript at call time. The token expires in ~1 second so it
  can never be replayed from saved headers. Playwright runs real Chromium
  so the JS runs natively and signs every request correctly.

Backend selection (automatic):
  1. Playwright   — if installed  (pip install playwright && playwright install chromium)
  2. curl_cffi    — fallback if Playwright not installed

Both backends return the same dict so nothing else in the codebase changes.
Celery tasks call _probe() directly — same function, just runs headless.

Install:
    pip install playwright --break-system-packages
    playwright install chromium

KEY FIX (v2):
  - x-hd and any other HMAC/signature headers are now ALWAYS stripped
    server-side before the request is fired, regardless of which backend
    is used. This means saved/cached curl configs never replay a stale
    signature — the browser regenerates a fresh one every time.
  - Added _SIGNATURE_HEADERS set for any header that is per-request signed.
  - Added backend detection logging so you can confirm Playwright vs curl_cffi
    at runtime (important: Celery workers need `playwright install chromium`
    run in the same venv/environment as the web process).
"""

from __future__ import annotations

import email.utils
import gzip
import json
import re
import time
import urllib.parse
import zlib
from datetime import datetime, timezone
from typing import Any

REGEN_CURL_SKIP = frozenset({
    ":authority", ":method", ":path", ":scheme",
}) | _STRIP | _SIGNATURE_HEADERS

try:
    import brotli as _brotli_mod
    _BROTLI_AVAILABLE = True
except ImportError:
    _BROTLI_AVAILABLE = False

try:
    from playwright.sync_api import sync_playwright
    _PLAYWRIGHT_OK = True
except ImportError:
    _PLAYWRIGHT_OK = False

try:
    from curl_cffi import requests as _tls
    _CURL_OK = True
except ImportError:
    _CURL_OK = False


# ─── Headers that must always be stripped ─────────────────────────────────────
# Browser DevTools copy-as-curl includes these. When replayed they cause
# 304 Not Modified (empty body) which we can't parse.
_STRIP = frozenset({
    "if-none-match", "if-match",
    "if-unmodified-since", "if-range",
})

# ─── Headers that must be regenerated with a fresh value each request ─────────
# if-modified-since: replaying a saved timestamp causes the server to return
# 304 Not Modified (empty body). We regenerate it to right now so the server
# always returns a full 200 response.
_REGENERATE_HEADERS: dict[str, callable] = {
    "if-modified-since": lambda: email.utils.format_datetime(
        datetime.now(timezone.utc), usegmt=True
    ),
}


# ─── Per-request signature headers ────────────────────────────────────────────
# These headers contain HMAC tokens that are generated by the site's own JS
# at request time and expire within ~1 second. They MUST be stripped from any
# saved/cached config so the browser can regenerate a fresh one each probe.
#
# Add any new per-request signature headers here as you discover them.
_SIGNATURE_HEADERS = frozenset({
    "x-hd",           # 1xbet — per-request HMAC, expires ~1s
    "x-request-sign", # generic pattern used by some bookmakers
    "x-signature",    # generic
    "x-ts",           # timestamp-based tokens
    "x-nonce",        # nonce tokens
})

import shlex
import urllib.parse

def _build_curl(
    method:  str,
    url:     str,
    headers: dict,
    params:  dict,
    body:    Any = None,
    cookies: str | None = None,
) -> str:
    """
    Build a human-readable curl command.
    - Params are properly URL-encoded (quote_via=urllib.parse.quote, not quote_plus)
    - Body is emitted as --data-raw for POST/PUT/PATCH
    - Cookies emitted as -b
    - GET requests omit the redundant -X GET flag
    - Output is multiline for readability
    """
    parts = ["curl"]

    # Only add -X for non-GET methods
    if method.upper() != "GET":
        parts.append(f"-X {method.upper()}")

    # URL + params
    qs       = urllib.parse.urlencode(params, quote_via=urllib.parse.quote) if params else ""
    full_url = f"{url}?{qs}" if qs else url
    parts.append(shlex.quote(full_url))

    # Headers
    for k, v in (headers or {}).items():
        parts.append(f"-H {shlex.quote(f'{k}: {v}')}")

    # Cookies
    if cookies:
        parts.append(f"-b {shlex.quote(cookies)}")

    # Body
    if body is not None:
        body_str = json.dumps(body) if isinstance(body, (dict, list)) else str(body)
        parts.append(f"--data-raw {shlex.quote(body_str)}")

    return " \\\n  ".join(parts)

# ─── Decompression ────────────────────────────────────────────────────────────

def _decompress(raw: bytes, encoding: str = "") -> tuple[bytes, str]:
    enc = encoding.lower()
    if "br" in enc and _BROTLI_AVAILABLE:
        try: return _brotli_mod.decompress(raw), "brotli"
        except Exception: pass
    if "gzip" in enc:
        try: return gzip.decompress(raw), "gzip"
        except Exception: pass
    if "deflate" in enc:
        for wb in (zlib.MAX_WBITS, -zlib.MAX_WBITS):
            try: return zlib.decompress(raw, wb), "deflate"
            except Exception: pass
    if len(raw) >= 2 and raw[0] == 0x78:
        for wb in (zlib.MAX_WBITS, -zlib.MAX_WBITS):
            try: return zlib.decompress(raw, wb), "zlib-magic"
            except Exception: pass
    if len(raw) >= 2 and raw[0] == 0x1F and raw[1] == 0x8B:
        try: return gzip.decompress(raw), "gzip-magic"
        except Exception: pass
    return raw, "none"


# ─── Shared helpers ───────────────────────────────────────────────────────────

def _parse_json(text: str) -> Any:
    for candidate in (text.strip(), re.sub(r"^\s*[\w$]+\s*\(", "", text).rstrip(");").strip()):
        try: return json.loads(candidate)
        except Exception: pass
    return None


def _find_array(parsed: Any) -> tuple[Any, str | None, int]:
    if isinstance(parsed, list):
        return (parsed[0] if parsed else None), None, len(parsed)
    if isinstance(parsed, dict):
        for k, v in parsed.items():
            if isinstance(v, list):
                return (v[0] if v else None), k, len(v)
    return None, None, 0


def _build_result(status: int | None, raw: bytes, encoding: str,
                  curl_cmd: str, latency: int, content_type: str = "",
                  regen_curl: str | None = None) -> dict:
    decompressed, method = _decompress(raw, encoding)
    if method != "none":
        print(f"[probe] {status} — {method} {len(raw)}→{len(decompressed)}b")
    else:
        print(f"[probe] {status} — {len(raw)}b")
    text   = decompressed.decode("utf-8", errors="replace")
    parsed = _parse_json(text)
    if parsed is None and text.strip():
        print(f"[probe] JSON parse failed. First 200: {text[:200]!r}")
    first_item, array_key, array_length = _find_array(parsed)
    ok = status is not None and 200 <= status < 300 and parsed is not None
    return {
        "ok": ok, "status": status, "latency_ms": latency,
        "content_type": content_type, "size_bytes": len(raw),
        "parsed": parsed, "response": parsed,
        "response_raw": text[:16_000],
        "first_item": first_item, "array_key": array_key, "array_length": array_length,
        "error": None if ok else f"HTTP {status}",
        "curl": curl_cmd,
        "curl_regenerated": regen_curl or curl_cmd,
    }


def _error_result(curl_cmd: str, error: str, latency: int) -> dict:
    return {
        "ok": False, "status": None, "latency_ms": latency,
        "content_type": "", "size_bytes": 0,
        "parsed": None, "response": None, "response_raw": "",
        "first_item": None, "array_key": None, "array_length": 0,
        "error": error, "curl": curl_cmd, "curl_regenerated": curl_cmd,
    }


# def _build_curl(method: str, url: str, params: dict,
#                 headers: dict, cookies: str | None, body: Any) -> str:
#     parts = ["curl"]
#     if method.upper() != "GET":
#         parts.append(f"-X {method.upper()}")
#     qs = urllib.parse.urlencode(params, quote_via=urllib.parse.quote) if params else ""
#     parts.append(f"'{url}?{qs}'" if qs else f"'{url}'")
#     for k, v in headers.items():
#         parts.append(f"-H '{k}: {v.replace(chr(39), chr(39)+chr(92)+chr(39)+chr(39))}'")
#     if cookies:
#         parts.append(f"-b '{cookies}'")
#     if body is not None:
#         s = json.dumps(body) if isinstance(body, (dict, list)) else str(body)
#         parts.append(f"--data-raw '{s}'")
#     return " \\\n  ".join(parts)


def _clean(headers: dict | None) -> dict:
    """
    Process incoming headers before firing a request:

      1. STRIP      — conditional cache headers that cause 304 empty responses
                      (if-none-match, if-match, if-unmodified-since, if-range)
      2. REGENERATE — headers whose saved value is stale but the header itself
                      is still valid if refreshed (if-modified-since → now)
      3. STRIP      — per-request HMAC/signature headers (x-hd etc.) whose tokens
                      expire in ~1s and must be regenerated by the browser JS

    This means saved/cached curl configs are always safe to replay — stale
    timestamps are refreshed, stale signatures are dropped for the browser
    to regenerate, and cache-conditional headers that would give empty
    responses are removed entirely.
    """
    stripped_cache = []
    regenerated    = []
    stripped_sig   = []
    result         = {}

    for k, v in (headers or {}).items():
        kl = k.strip().lower()

        if kl in _STRIP:
            stripped_cache.append(k)
            continue

        if kl in _REGENERATE_HEADERS:
            fresh = _REGENERATE_HEADERS[kl]()
            result[k] = fresh
            regenerated.append(f"{k}: {v!r} → {fresh!r}")
            continue

        if kl in _SIGNATURE_HEADERS:
            stripped_sig.append(k)
            continue

        result[k] = v

    if stripped_cache:
        print(f"[probe] Stripped cache-conditional header(s): {', '.join(stripped_cache)}")
    if regenerated:
        print(f"[probe] Regenerated header(s): {'; '.join(regenerated)}")
    if stripped_sig:
        print(f"[probe] Stripped per-request signature header(s): {', '.join(stripped_sig)} "
              f"— browser will regenerate fresh tokens")

    return result


# ═══════════════════════════════════════════════════════════════════════════════
# ─── Backend 1: Playwright ────────────────────────────────────────────────────
# ═══════════════════════════════════════════════════════════════════════════════

def _probe_playwright(url, method, headers, params, body, timeout) -> dict:
    method  = (method or "GET").upper()
    params  = {str(k): str(v) for k, v in (params or {}).items() if str(k).strip()}
    # _clean now strips both cache headers AND signature headers (x-hd etc.)
    headers = _clean(headers)

    # Build query string with minimal encoding — only encode characters that
    # are truly unsafe in a URL. Using quote_via=urllib.parse.quote (not
    # quote_plus) preserves spaces as %20 rather than '+', and avoids
    # double-encoding values that were already decoded by parseCurl on the
    # frontend (e.g. %3D → = → %253D if encoded twice).
    qs       = urllib.parse.urlencode(params, quote_via=urllib.parse.quote) if params else ""
    full_url = f"{url}?{qs}" if qs else url

    cookie_str: str | None = None
    extra_headers: dict    = {}
    user_agent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36"

    for k, v in headers.items():
        kl = k.lower()
        if kl == "cookie":
            cookie_str = v
        elif kl == "user-agent":
            user_agent = v
        else:
            # x-hd is already gone from headers thanks to _clean() above,
            # but keep this guard as a safety net
            if kl in _SIGNATURE_HEADERS:
                print(f"[probe] Safety-net strip: {k} (should have been caught by _clean)")
                continue
            extra_headers[k] = v

    curl_cmd = _build_curl( method  = method,
    url     = url,
    headers = {k: v for k, v in headers.items() if k.lower() not in _REGEN_CURL_SKIP},
    params  = params,
    body    = body,)
    print(f"[probe] Backend: Playwright (headless Chromium)")
    print(f"Executing (playwright): {curl_cmd}")

    t0 = time.perf_counter()
    try:
        with sync_playwright() as pw:
            browser = pw.chromium.launch(
                headless=True,
                args=[
                    "--no-sandbox",
                    "--disable-blink-features=AutomationControlled",
                    "--disable-dev-shm-usage",
                    "--disable-setuid-sandbox",
                ],
            )
            context = browser.new_context(
                user_agent=user_agent,
                extra_http_headers=extra_headers,
            )

            if cookie_str:
                parsed_url = urllib.parse.urlparse(full_url)
                cookies_to_add = []
                for part in cookie_str.split(";"):
                    part = part.strip()
                    if "=" in part:
                        name, _, val = part.partition("=")
                        cookies_to_add.append({
                            "name":   name.strip(),
                            "value":  val.strip(),
                            "domain": parsed_url.hostname or "",
                            "path":   "/",
                        })
                if cookies_to_add:
                    context.add_cookies(cookies_to_add)

            page = context.new_page()
            captured: dict = {}

            def on_response(response):
                try:
                    resp_base = response.url.split("?")[0]
                    req_base  = full_url.split("?")[0]
                    if resp_base == req_base or response.url == full_url:
                        # Capture the ACTUAL headers the browser sent, including
                        # the freshly generated x-hd so we can show them in the UI
                        req_headers = dict(response.request.headers)
                        xhd = req_headers.get("x-hd", "")
                        if xhd:
                            print(f"[probe] browser-generated x-hd: {xhd[:40]}…")
                        captured["status"]          = response.status
                        captured["content_type"]    = response.headers.get("content-type", "")
                        captured["encoding"]        = response.headers.get("content-encoding", "")
                        captured["body"]            = response.body()
                        captured["actual_headers"]  = req_headers  # ← real browser headers
                except Exception:
                    pass

            page.on("response", on_response)

            if method == "GET":
                # Navigate to the origin root first so the site's JS loads
                # and can sign outgoing XHRs with a fresh per-request token
                # (e.g. 1xbet x-hd). Using the root works for ANY bookmaker —
                # the old hardcoded /en/live only worked for 1xbet.
                origin     = urllib.parse.urlparse(full_url)
                origin_url = f"{origin.scheme}://{origin.netloc}/"
                print(f"[probe] Navigating to origin first: {origin_url}")
                try:
                    page.goto(origin_url, timeout=timeout * 1000, wait_until="domcontentloaded")
                except Exception as nav_exc:
                    # Some origins return non-200 for root but still load JS —
                    # ignore navigation errors and proceed with the fetch anyway.
                    print(f"[probe] Origin navigation warning (non-fatal): {nav_exc}")

                # Now trigger the actual API call via JS fetch so the
                # site's signing JS runs in the correct page context
                result = page.evaluate(f"""
                async () => {{
                    const resp = await fetch({json.dumps(full_url)}, {{
                        method: 'GET',
                        credentials: 'include',
                    }});
                    const buf = await resp.arrayBuffer();
                    return {{
                        status:      resp.status,
                        contentType: resp.headers.get('content-type') || '',
                        body:        Array.from(new Uint8Array(buf)),
                    }};
                }}
                """)
                captured = {
                    "status":       result["status"],
                    "content_type": result["contentType"],
                    "encoding":     "",
                    "body":         bytes(result["body"]),
                }
            else:
                body_json  = json.dumps(body) if isinstance(body, (dict, list)) else (body or "")
                headers_js = json.dumps(extra_headers)
                result = page.evaluate(f"""
                async () => {{
                    const resp = await fetch({json.dumps(full_url)}, {{
                        method:      {json.dumps(method)},
                        headers:     {headers_js},
                        body:        {json.dumps(body_json) if body_json else 'undefined'},
                        credentials: 'include',
                    }});
                    const buf = await resp.arrayBuffer();
                    return {{
                        status:      resp.status,
                        contentType: resp.headers.get('content-type') || '',
                        body:        Array.from(new Uint8Array(buf)),
                    }};
                }}
                """)
                captured = {
                    "status":       result["status"],
                    "content_type": result["contentType"],
                    "encoding":     "",
                    "body":         bytes(result["body"]),
                }

            browser.close()

        latency = int((time.perf_counter() - t0) * 1000)

        if not captured:
            return _error_result(curl_cmd, "No response captured by Playwright", latency)

        raw: bytes = captured.get("body", b"")
        if isinstance(raw, list):
            raw = bytes(raw)

        # Build a regenerated curl from the actual headers the browser used.
        # This includes the live x-hd token so the user can see/copy it.
        actual_hdrs = captured.get("actual_headers", {})
        actual_cookie = actual_hdrs.pop("cookie", None)
        regen_curl = _build_curl(
            method   = method,
            url      = url,
            params   = params,
            headers  = {k: v for k, v in actual_hdrs.items()
                        if k.lower() not in (":authority", ":method", ":path", ":scheme")},
            cookies  = actual_cookie,
            body     = body,
        ) if actual_hdrs else curl_cmd

        return _build_result(
            status       = captured.get("status"),
            raw          = raw,
            encoding     = captured.get("encoding", ""),
            curl_cmd     = curl_cmd,
            latency      = latency,
            content_type = captured.get("content_type", ""),
            regen_curl   = regen_curl,
        )

    except Exception as exc:
        latency = int((time.perf_counter() - t0) * 1000)
        print(f"[probe-playwright] Exception: {exc}")
        return _error_result(curl_cmd, str(exc), latency)

# ═══════════════════════════════════════════════════════════════════════════════
# ─── Backend 2: curl_cffi (fallback) ─────────────────────────────────────────
# ═══════════════════════════════════════════════════════════════════════════════

_BROWSER_DEFAULTS: dict[str, str] = {
    "user-agent":         "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36",
    "accept":             "application/json, text/plain, */*",
    "accept-language":    "en-GB,en-US;q=0.9,en;q=0.8",
    "sec-ch-ua":          '"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"',
    "sec-ch-ua-mobile":   "?0",
    "sec-ch-ua-platform": '"macOS"',
    "sec-fetch-dest":     "empty",
    "sec-fetch-mode":     "cors",
    "sec-fetch-site":     "same-origin",
    "connection":         "keep-alive",
}

_CHROME_TARGETS = [
    "chrome131", "chrome124", "chrome123", "chrome120", "chrome119",
    "chrome116", "chrome110", "chrome107", "chrome104",
]


def _probe_curl(url, method, headers, params, body, timeout) -> dict:
    method  = (method or "GET").upper()
    params  = {str(k): str(v) for k, v in (params or {}).items() if str(k).strip()}
    # _clean strips cache headers AND signature headers (x-hd etc.)
    headers = _clean(headers)

    merged = {k.lower(): v for k, v in _BROWSER_DEFAULTS.items()}
    for k, v in headers.items():
        merged[k.strip().lower()] = v
    user_sent_ae = any(k.lower() == "accept-encoding" for k in headers)
    if not user_sent_ae:
        merged["accept-encoding"] = "gzip, deflate, br"

    cookie_val: str | None = None
    display_h: dict = {}
    for k, v in merged.items():
        if k == "cookie":
            cookie_val = v
        elif k == "accept-encoding" and not user_sent_ae:
            pass
        else:
            display_h[k] = v

    curl_cmd = _build_curl(method, url, params, display_h, cookie_val, body)
    print(f"[probe] Backend: curl_cffi (Playwright not available — x-hd cannot be regenerated!)")
    print(f"[probe] WARNING: Sites that require per-request HMAC (1xbet x-hd) will return 406.")
    print(f"[probe] Fix: pip install playwright --break-system-packages && playwright install chromium")
    print(f"Executing (curl_cffi): {curl_cmd}")

    t0   = time.perf_counter()
    resp = None
    used = _CHROME_TARGETS[0]

    for target in _CHROME_TARGETS:
        try:
            resp = _tls.request(
                method=method, url=url, headers=merged, params=params,
                json=body if body and isinstance(body, (dict, list)) else None,
                data=body if body and isinstance(body, str) else None,
                impersonate=target, timeout=timeout,
            )
            used = target
            if resp.status_code not in (403, 406):
                break
            if len(resp.content) == 0 and resp.status_code == 406:
                print(f"[probe] 406 + 0-byte — HMAC signature required (x-hd), curl_cffi cannot generate it. "
                      f"Install Playwright to fix this.")
                break
            print(f"[probe] {resp.status_code} with {target} — trying next…")
        except Exception as exc:
            if any(x in str(exc).lower() for x in ("ssl", "tls", "handshake", "connect")):
                print(f"[probe] {target} TLS error — trying next…")
                continue
            break

    latency = int((time.perf_counter() - t0) * 1000)
    if resp is None:
        return _error_result(curl_cmd, "All targets failed", latency)

    return _build_result(
        status       = resp.status_code,
        raw          = resp.content,
        encoding     = resp.headers.get("Content-Encoding", ""),
        curl_cmd     = curl_cmd,
        latency      = latency,
        content_type = resp.headers.get("Content-Type", ""),
    )


# ═══════════════════════════════════════════════════════════════════════════════
# ─── Public API ──────────────────────────────────────────────────────────────
# ═══════════════════════════════════════════════════════════════════════════════

def _probe(
    url:     str,
    method:  str         = "GET",
    headers: dict | None = None,
    params:  dict | None = None,
    body:    Any         = None,
    timeout: int         = 30,
) -> dict:
    """
    Fire an HTTP request. Returns a structured result dict.

    Uses Playwright (headless Chromium) when available so that
    per-request HMAC tokens (e.g. 1xbet x-hd) are generated by the
    site's own JS. Falls back to curl_cffi if Playwright is not installed,
    but note that curl_cffi CANNOT handle sites requiring x-hd — it will
    always return 406 for those endpoints.

    KEY BEHAVIOUR: Any header in _SIGNATURE_HEADERS (x-hd, x-signature etc.)
    is ALWAYS stripped before the request is fired, even if it was present in
    the saved session config. This ensures cached curl configs never replay a
    stale token — the browser regenerates a fresh one every time.

    Same signature and response shape regardless of backend — safe to
    call from Flask views, Celery tasks, or CLI scripts.
    """
    
    # 🚨 ANTI-BOT FIX: Preserve query parameter order
    # When loading params from a database (like JSONB), or passing them into 
    # underlying libraries (like curl_cffi), the dictionary keys often get 
    # sorted alphabetically. We build the query string manually right here 
    # to lock in the exact insertion order so the WAF receives the 
    # specific URL fingerprint it expects.
    if params:
        clean_params = {str(k): str(v) for k, v in params.items() if str(k).strip()}
        if clean_params:
            qs = urllib.parse.urlencode(clean_params, quote_via=urllib.parse.quote)
            sep = "&" if "?" in url else "?"
            url = f"{url}{sep}{qs}"
        
        # Setting params to None forces the backends to use the raw pre-assembled URL 
        # instead of attempting to rebuild (and incorrectly sort) them.
        params = None

    if _PLAYWRIGHT_OK:
        return _probe_playwright(url, method, headers, params, body, timeout)
    if _CURL_OK:
        return _probe_curl(url, method, headers, params, body, min(timeout, 15))
    
    return _error_result(url, "Neither playwright nor curl_cffi is installed. "
                         "Run: pip install playwright && playwright install chromium", 0)


# ─── Placeholder detection (unchanged) ───────────────────────────────────────

_ROLE_HINTS: list[tuple[re.Pattern, str]] = [
    (re.compile(r"^(match_?id|event_?id|game_?id|fixture_?id|^Id$)", re.I), "match_id"),
    (re.compile(r"^(sport_?id|^sport$|SportId)",                     re.I), "sport_id"),
    (re.compile(r"^(league_?id|competition_?id|champ_?id|ChampId)",  re.I), "league_id"),
    (re.compile(r"^(team_?id|home_?id|T1Id|away_?id|T2Id)",         re.I), "team_id"),
    (re.compile(r"^(country_?id|^country$|CountryId)",               re.I), "country_id"),
    (re.compile(r"^(partner_?id|^partner$)",                         re.I), "partner_id"),
]


def _flatten_item(obj: Any, prefix: str = "", depth: int = 0) -> list[tuple[str, str]]:
    if depth > 5 or obj is None: return []
    if isinstance(obj, (str, int, float, bool)) and prefix: return [(prefix, str(obj))]
    if isinstance(obj, list):
        out = []
        for i, v in enumerate(obj[:5]): out.extend(_flatten_item(v, f"{prefix}[{i}]", depth+1))
        return out
    if isinstance(obj, dict):
        out = []
        for k, v in obj.items():
            path = f"{prefix}.{k}" if prefix else k
            if isinstance(v, (str, int, float, bool)): out.append((path, str(v)))
            else: out.extend(_flatten_item(v, path, depth+1))
        return out
    return []


def _field_to_var_name(field_path: str) -> str:
    leaf = field_path.split(".")[-1].split("[")[0]
    for pattern, role in _ROLE_HINTS:
        if pattern.search(leaf): return role
    clean = re.sub(r"([A-Z])", r"_\1", leaf).lower().strip("_")
    return re.sub(r"[^a-z0-9_]", "_", clean).strip("_") or "value"


def _detect_placeholders(markets_url: str, markets_params: dict,
                          list_item: dict, min_value_len: int = 4) -> dict:
    try:
        purl       = urllib.parse.urlparse(markets_url)
        url_params = dict(urllib.parse.parse_qsl(purl.query))
        base_url   = urllib.parse.urlunparse(purl._replace(query=""))
    except Exception:
        url_params = {}; base_url = markets_url

    all_params = {**markets_params, **url_params}
    flat       = _flatten_item(list_item)
    detected:        list[dict] = []
    placeholder_map: dict       = {}
    used_vars:       set        = set()

    for field_path, raw_value in flat:
        value = raw_value.strip()
        if len(value) < min_value_len: continue
        if value.lower() in ("true","false","null","none","undefined"): continue
        var_name = _field_to_var_name(field_path)
        base_var = var_name; n = 2
        while var_name in used_vars: var_name = f"{base_var}_{n}"; n += 1
        placeholder = f"{{{{{var_name}}}}}"; found = False
        if value in base_url:
            base_url = base_url.replace(value, placeholder, 1)
            detected.append({"var":var_name,"field_path":field_path,"value":value,"location":"url-path"})
            placeholder_map[var_name] = field_path; used_vars.add(var_name); found = True
        if not found:
            for pk, pv in list(all_params.items()):
                if str(pv).strip() == value:
                    all_params[pk] = placeholder
                    detected.append({"var":var_name,"field_path":field_path,"value":value,"location":f"param:{pk}"})
                    placeholder_map[var_name] = field_path; used_vars.add(var_name); found = True; break

    qs            = urllib.parse.urlencode(all_params) if all_params else ""
    suggested_url = f"{base_url}?{qs}" if qs else base_url
    return {"suggested_url":suggested_url,"suggested_params":all_params,
            "detected":detected,"placeholder_map":placeholder_map}