"""
app/views/odds_feed/monitor_view.py
====================================
Serves the live health report generated by tasks_ops.build_health_report.

Register in create_app():
    from app.views.odds_feed.monitor_view import bp_monitor
    app.register_blueprint(bp_monitor)

Endpoints
─────────
  GET /api/monitor/report           Full latest report (JSON)
  GET /api/monitor/report/history   Last 60 snapshots  (1 hour of 1-min ticks)
  GET /api/monitor/jobs             Last N job log entries
  GET /api/monitor/jobs/stream      SSE stream — pushes a new line per job entry
  GET /api/monitor/sports           Quick per-sport cache summary
  GET /api/monitor/dashboard        Human-readable HTML dashboard
"""

from __future__ import annotations

import json
import time
from datetime import datetime, timezone

from flask import Blueprint, Response, request, stream_with_context

bp_monitor = Blueprint("monitor", __name__, url_prefix="/api/monitor")

_GREEN  = "#22c55e"
_RED    = "#ef4444"
_YELLOW = "#eab308"
_GRAY   = "#6b7280"


def _now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _cache_get(key: str):
    try:
        from app.workers.celery_tasks import cache_get
        return cache_get(key)
    except Exception:
        return None


def _redis():
    try:
        from app.workers.celery_tasks import _redis as _r
        return _r()
    except Exception:
        return None


# ─────────────────────────────────────────────────────────────────────────────
# JSON endpoints
# ─────────────────────────────────────────────────────────────────────────────

@bp_monitor.route("/report")
def get_report():
    """
    GET /api/monitor/report
    Returns the latest health report built by build_health_report task (every 60 s).
    If the report is stale or missing, builds one synchronously.
    """
    report = _cache_get("monitor:report")
    if not report:
        # Build on-demand if beat hasn't fired yet
        try:
            from app.workers.tasks_ops import build_health_report
            report = build_health_report()
        except Exception as exc:
            return {"ok": False, "error": str(exc)}, 500

    return {"ok": True, **report}


@bp_monitor.route("/report/history")
def get_report_history():
    """
    GET /api/monitor/report/history
    Returns the last 60 health report summaries (one per minute = 1 hour).
    """
    r = _redis()
    if not r:
        return {"ok": False, "error": "Redis unavailable"}, 503

    limit = min(int(request.args.get("limit", 60)), 60)
    raw   = r.lrange("monitor:report_history", 0, limit - 1)
    history = []
    for item in raw:
        try:
            history.append(json.loads(item))
        except Exception:
            pass

    return {
        "ok":      True,
        "total":   len(history),
        "history": history,
        "ts":      _now(),
    }


@bp_monitor.route("/jobs")
def get_jobs():
    """
    GET /api/monitor/jobs?limit=100&bookmaker=sp&sport=soccer&status=error
    Returns recent job log entries from the rolling Redis list.
    """
    r = _redis()
    if not r:
        return {"ok": False, "error": "Redis unavailable"}, 503

    limit     = min(int(request.args.get("limit", 100)), 500)
    bk_filter = request.args.get("bookmaker", "").lower()
    sp_filter = request.args.get("sport", "").lower()
    st_filter = request.args.get("status", "").lower()

    raw  = r.lrange("monitor:job_log", 0, 499)
    jobs = []
    for item in raw:
        try:
            entry = json.loads(item)
            if bk_filter and entry.get("bookmaker", "").lower() != bk_filter:
                continue
            if sp_filter and entry.get("sport", "").lower() != sp_filter:
                continue
            if st_filter and entry.get("status", "").lower() != st_filter:
                continue
            jobs.append(entry)
        except Exception:
            pass
        if len(jobs) >= limit:
            break

    ok_count   = sum(1 for j in jobs if j.get("status") == "ok")
    err_count  = sum(1 for j in jobs if j.get("status") == "error")
    emp_count  = sum(1 for j in jobs if j.get("status") == "empty")

    return {
        "ok":         True,
        "total":      len(jobs),
        "ok_count":   ok_count,
        "err_count":  err_count,
        "empty_count": emp_count,
        "jobs":       jobs,
        "ts":         _now(),
    }


@bp_monitor.route("/sports")
def get_sports():
    """
    GET /api/monitor/sports
    Quick per-sport cache summary without the full report payload.
    """
    from app.workers.tasks_ops import PERSIST_SPORTS

    summary = []
    for sport in PERSIST_SPORTS:
        u = _cache_get(f"combined:upcoming:{sport}") or {}
        l = _cache_get(f"combined:live:{sport}")     or {}
        u_m = u.get("matches", [])
        l_m = l.get("matches", [])
        summary.append({
            "sport":           sport,
            "upcoming":        len(u_m),
            "live":            len(l_m),
            "arbs":            sum(1 for m in u_m + l_m if m.get("has_arb")),
            "evs":             sum(1 for m in u_m + l_m if m.get("has_ev")),
            "bk_counts_up":    u.get("bk_counts", {}),
            "bk_counts_lv":    l.get("bk_counts", {}),
            "harvested_at_up": u.get("harvested_at"),
            "harvested_at_lv": l.get("harvested_at"),
            "populated":       bool(u_m or l_m),
        })

    populated = sum(1 for s in summary if s["populated"])
    return {
        "ok":              True,
        "total_sports":    len(PERSIST_SPORTS),
        "populated_sports": populated,
        "sports":          summary,
        "ts":              _now(),
    }


# ─────────────────────────────────────────────────────────────────────────────
# SSE job stream  (real-time job log tail)
# ─────────────────────────────────────────────────────────────────────────────

@bp_monitor.route("/jobs/stream")
def jobs_stream():
    """
    GET /api/monitor/jobs/stream
    SSE stream: pushes a new event for every job written to the log.
    Connect once and watch harvest activity in real time.
    """
    @stream_with_context
    def generate():
        r = _redis()
        if not r:
            yield f"data: {json.dumps({'error': 'Redis unavailable'})}\n\n"
            return

        yield f"data: {json.dumps({'type': 'connected', 'ts': _now()})}\n\n"

        # Track the list length — new entries are prepended (lpush)
        try:
            last_len = r.llen("monitor:job_log")
        except Exception:
            last_len = 0

        last_ka = time.monotonic()
        while True:
            time.sleep(1)
            try:
                current_len = r.llen("monitor:job_log")
                new_count   = current_len - last_len
                if new_count > 0:
                    # New entries are at the head of the list
                    new_entries = r.lrange("monitor:job_log", 0, new_count - 1)
                    for raw in reversed(new_entries):   # oldest first
                        try:
                            entry = json.loads(raw)
                            yield f"data: {json.dumps({'type': 'job', **entry})}\n\n"
                        except Exception:
                            pass
                    last_len = current_len
            except Exception:
                pass

            if time.monotonic() - last_ka >= 15:
                yield f": keep-alive {_now()}\n\n"
                last_ka = time.monotonic()

    return Response(generate(), headers={
        "Content-Type":      "text/event-stream",
        "Cache-Control":     "no-cache",
        "X-Accel-Buffering": "no",
        "Connection":        "keep-alive",
    })


# ─────────────────────────────────────────────────────────────────────────────
# HTML dashboard
# ─────────────────────────────────────────────────────────────────────────────

@bp_monitor.route("/dashboard")
def dashboard():
    """
    GET /api/monitor/dashboard
    Human-readable HTML dashboard that auto-refreshes every 60 seconds.
    Shows overall health, per-sport cache state, and the last 20 jobs.
    """
    report = _cache_get("monitor:report") or {}
    overall = report.get("overall", {})
    worker  = report.get("worker", {})
    totals  = report.get("totals", {})
    sports  = report.get("sports", [])
    checks  = report.get("checks", [])
    jobs    = report.get("recent_jobs", [])
    gen_at  = report.get("generated_at", "—")

    healthy    = overall.get("healthy", False)
    hdr_color  = _GREEN if healthy else _RED
    hdr_label  = "● HEALTHY" if healthy else "● ISSUES DETECTED"

    def _badge(val: bool) -> str:
        c = _GREEN if val else _RED
        t = "✔" if val else "✗"
        return f'<span style="color:{c};font-weight:bold">{t}</span>'

    def _status_color(s: str) -> str:
        return {"ok": _GREEN, "error": _RED, "empty": _YELLOW}.get(s, _GRAY)

    sport_rows = ""
    for s in sports:
        pop_color = _GREEN if s.get("populated") else _RED
        sport_rows += f"""
        <tr>
          <td>{s['sport']}</td>
          <td style="color:{pop_color}">{s['status']}</td>
          <td>{s['upcoming_count']}</td>
          <td>{s['live_count']}</td>
          <td>{s.get('upcoming_arbs',0) + s.get('live_arbs',0)}</td>
          <td>{s.get('upcoming_evs',0)  + s.get('live_evs',0)}</td>
          <td style="font-size:11px">{s.get('harvested_at_up','—')}</td>
        </tr>"""

    check_rows = ""
    for c in checks:
        check_rows += f"""
        <tr>
          <td>{_badge(c['passed'])}</td>
          <td>{c['name']}</td>
          <td style="color:{_GRAY};font-size:12px">{c.get('detail','')}</td>
        </tr>"""

    job_rows = ""
    for j in jobs[:20]:
        sc = _status_color(j.get("status", ""))
        job_rows += f"""
        <tr style="font-size:12px">
          <td style="color:{_GRAY}">{j.get('ts','')}</td>
          <td>{j.get('bookmaker','')}</td>
          <td>{j.get('sport','')}</td>
          <td>{j.get('mode','')}</td>
          <td>{j.get('count',0)}</td>
          <td style="color:{sc}">{j.get('status','')}</td>
          <td style="color:{_GREEN}">{j.get('unified_ok',0)}</td>
          <td style="color:{_RED}">{j.get('unified_fail',0)}</td>
          <td>{j.get('latency_ms',0)}ms</td>
          <td style="color:{_RED};font-size:11px">{j.get('detail','')}</td>
        </tr>"""

    html = f"""<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="refresh" content="60">
  <title>Odds Kenya — Monitor</title>
  <style>
    body  {{ font-family: monospace; background:#0f172a; color:#e2e8f0; margin:0; padding:20px }}
    h1    {{ color:{hdr_color}; margin-bottom:4px }}
    h2    {{ color:#94a3b8; margin:24px 0 8px }}
    .meta {{ color:#64748b; font-size:12px; margin-bottom:20px }}
    .grid {{ display:grid; grid-template-columns:repeat(4,1fr); gap:12px; margin-bottom:24px }}
    .card {{ background:#1e293b; border-radius:8px; padding:16px }}
    .card .label {{ color:#64748b; font-size:12px }}
    .card .value {{ font-size:28px; font-weight:bold; margin-top:4px }}
    table {{ width:100%; border-collapse:collapse; background:#1e293b;
             border-radius:8px; overflow:hidden }}
    th    {{ background:#334155; padding:8px 12px; text-align:left;
             font-size:12px; color:#94a3b8; text-transform:uppercase }}
    td    {{ padding:7px 12px; border-bottom:1px solid #334155; font-size:13px }}
    tr:last-child td {{ border-bottom:none }}
    .refresh {{ color:#64748b; font-size:11px; float:right; margin-top:-40px }}
  </style>
</head>
<body>
  <h1>{hdr_label}</h1>
  <div class="meta">
    Generated: {gen_at} &nbsp;|&nbsp;
    Worker: {'alive ✔' if worker.get('alive') else 'dead ✗'} &nbsp;|&nbsp;
    Heartbeat age: {worker.get('heartbeat_age_s','?')}s &nbsp;|&nbsp;
    PID: {worker.get('pid','?')}
  </div>
  <div class="refresh">Auto-refreshes every 60s</div>

  <div class="grid">
    <div class="card">
      <div class="label">Upcoming Matches</div>
      <div class="value" style="color:{_GREEN}">{totals.get('upcoming_matches',0)}</div>
    </div>
    <div class="card">
      <div class="label">Live Matches</div>
      <div class="value" style="color:{_GREEN}">{totals.get('live_matches',0)}</div>
    </div>
    <div class="card">
      <div class="label">Arb Opportunities</div>
      <div class="value" style="color:{_YELLOW}">{totals.get('arb_opportunities',0)}</div>
    </div>
    <div class="card">
      <div class="label">EV Opportunities</div>
      <div class="value" style="color:{_YELLOW}">{totals.get('ev_opportunities',0)}</div>
    </div>
  </div>

  <h2>System Checks ({overall.get('passed',0)}/{overall.get('total_checks',0)} passed)</h2>
  <table>
    <tr><th></th><th>Check</th><th>Detail</th></tr>
    {check_rows}
  </table>

  <h2>Sports Cache ({len([s for s in sports if s.get('populated')])}/{len(sports)} populated)</h2>
  <table>
    <tr><th>Sport</th><th>Status</th><th>Upcoming</th><th>Live</th>
        <th>Arbs</th><th>EVs</th><th>Last Harvest</th></tr>
    {sport_rows}
  </table>

  <h2>Recent Jobs (last 20)</h2>
  <table>
    <tr><th>Time</th><th>Bookmaker</th><th>Sport</th><th>Mode</th>
        <th>Count</th><th>Status</th><th>OK</th><th>Fail</th>
        <th>Latency</th><th>Detail</th></tr>
    {job_rows if job_rows else '<tr><td colspan="10" style="color:#64748b">No jobs yet</td></tr>'}
  </table>

  <br>
  <div style="color:#475569;font-size:11px">
    JSON endpoints: &nbsp;
    <a href="/api/monitor/report" style="color:#60a5fa">/api/monitor/report</a> &nbsp;
    <a href="/api/monitor/report/history" style="color:#60a5fa">/api/monitor/report/history</a> &nbsp;
    <a href="/api/monitor/jobs" style="color:#60a5fa">/api/monitor/jobs</a> &nbsp;
    <a href="/api/monitor/sports" style="color:#60a5fa">/api/monitor/sports</a>
  </div>
</body>
</html>"""

    return Response(html, content_type="text/html")